// <auto-generated />
using System;
using Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(MySQLDbContext))]
    [Migration("20260307212003_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Entities.ArquivoLido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ArquivosLidos");
                });

            modelBuilder.Entity("Core.Entities.AtivoDistribuido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DistribuicaoClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DistribuicaoClienteId");

                    b.ToTable("AtivoDistribuido");
                });

            modelBuilder.Entity("Core.Entities.Cesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cestas");
                });

            modelBuilder.Entity("Core.Entities.ClienteCadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core.Entities.ContaGrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("Core.Entities.ContaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ContaMaster");
                });

            modelBuilder.Entity("Core.Entities.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoBDI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMercado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("Core.Entities.CustodiaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("CustodiasFilhotes");
                });

            modelBuilder.Entity("Core.Entities.CustodiaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId");

                    b.ToTable("CustodiaMaster");
                });

            modelBuilder.Entity("Core.Entities.DetalheOrdem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("DetalheOrdem");
                });

            modelBuilder.Entity("Core.Entities.DistribuicaoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorAporte")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("DistribuicoesCliente");
                });

            modelBuilder.Entity("Core.Entities.ItemCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CestaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CotacaoAtual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("Core.Entities.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("Core.Entities.AtivoDistribuido", b =>
                {
                    b.HasOne("Core.Entities.DistribuicaoCliente", "DistribuicaoCliente")
                        .WithMany("Ativos")
                        .HasForeignKey("DistribuicaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistribuicaoCliente");
                });

            modelBuilder.Entity("Core.Entities.ContaGrafica", b =>
                {
                    b.HasOne("Core.Entities.ClienteCadastro", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("Core.Entities.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Core.Entities.CustodiaFilhote", b =>
                {
                    b.HasOne("Core.Entities.ContaGrafica", "ContaGrafica")
                        .WithMany()
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("Core.Entities.CustodiaMaster", b =>
                {
                    b.HasOne("Core.Entities.ContaMaster", "ContaMaster")
                        .WithMany("ItensCustodia")
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("Core.Entities.DetalheOrdem", b =>
                {
                    b.HasOne("Core.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Detalhes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("Core.Entities.ItemCesta", b =>
                {
                    b.HasOne("Core.Entities.Cesta", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("Core.Entities.Cesta", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Core.Entities.ClienteCadastro", b =>
                {
                    b.Navigation("ContaGrafica")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.ContaMaster", b =>
                {
                    b.Navigation("ItensCustodia");
                });

            modelBuilder.Entity("Core.Entities.DistribuicaoCliente", b =>
                {
                    b.Navigation("Ativos");
                });

            modelBuilder.Entity("Core.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Detalhes");
                });
#pragma warning restore 612, 618
        }
    }
}
